packages:
  - apps/*
  - packages/*
overrides:
  image-size: npm:image-size-next@2.1.1
minimumReleaseAgeExclude:
  - '@supabase/cli-darwin-arm64@2.117.0'
  - '@supabase/cli-darwin-x64@2.117.0'
  - '@supabase/cli-linux-arm64-musl@2.117.0'
  - '@supabase/cli-linux-arm64@2.117.0'
  - '@supabase/cli-linux-x64-musl@2.117.0'
  - '@supabase/cli-linux-x64@2.117.0'
  - '@supabase/cli-windows-arm64@2.117.0'
  - '@supabase/cli-windows-x64@2.117.0'
  - supabase@2.117.0
  - image-size-next@2.1.1
