/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getV1Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enrollByInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordTrueMvpConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/display-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountDisplayName"];
        put: operations["setAccountDisplayName"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitWorkoutCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueGroupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-invitations/{invitationId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeGroupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptGroupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-invitations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["previewGroupInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-memberships/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-memberships/weekly-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWeeklyTarget"];
        put: operations["setWeeklyTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/group-memberships/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentGroupMembership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member-home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMemberHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{notificationId}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openNotification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/social-interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSocialInteraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/members/{membershipId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["removeGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGroupMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/pending-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPendingGroupInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/current-week-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentWeekProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{groupId}/finalized-weekly-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFinalizedWeeklyHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Current and immediately previous baseline wire versions.
             * @enum {integer}
             */
            contractVersion: 0 | 1;
            /** @enum {string} */
            status: "ok";
        };
        ApiErrorResponse: {
            /** @constant */
            contractVersion: 1;
            error: components["schemas"]["ApiError"];
        };
        ApiError: {
            /** @enum {string} */
            code: "unauthorized" | "invalid_request" | "denied" | "idempotency_required" | "idempotency_conflict" | "domain_failure";
            message: string;
            retryable: boolean;
        };
        SubmitWorkoutCheckinRequest: {
            /** Format: uuid */
            workoutCheckinId: string;
            /** @enum {string} */
            activityType: "strength" | "cardio" | "class" | "sport" | "mixed";
            completedAt: components["schemas"]["UtcInstant"];
            durationMinutes: number;
            /** @enum {string} */
            perceivedIntensity: "low" | "moderate" | "high";
            /** @constant */
            selfReportAttested: true;
        };
        CreateGroupRequest: {
            /** Format: uuid */
            groupId: string;
            /** Format: uuid */
            membershipId: string;
            name: string;
            timeZone: string;
            weeklyTarget: number;
        };
        IssueGroupInvitationRequest: {
            /** Format: uuid */
            invitationId: string;
            /** Format: email */
            email: string;
        };
        AcceptGroupInvitationRequest: {
            token: string;
            /** Format: uuid */
            membershipId: string;
            recurringTarget: number;
            currentTarget: number;
        };
        InvitationPreviewResponse: {
            /** @constant */
            contractVersion: 1;
            data: {
                groupName: string;
                memberCount: number;
                /** Format: date-time */
                weekEndsAt: string;
            };
        };
        SetWeeklyTargetRequest: {
            weeklyTarget: number;
        };
        DeleteAccountRequest: {
            /** @constant */
            confirmation: true;
            /** @description Fresh email code required by active PWA API */
            otpCode: string;
        };
        SetDisplayNameRequest: {
            displayName: string;
        };
        AccountDisplayNameResponse: {
            /** @constant */
            contractVersion: 1;
            data: {
                displayName: string | null;
            };
        };
        EnrollmentRequest: {
            /** Format: email */
            email: string;
            token: string;
        };
        EnrollmentResponse: {
            /** @constant */
            contractVersion: 1;
            data: {
                /** @constant */
                message: "If invitation is eligible, request a sign-in code.";
            };
        };
        ConsentRequest: {
            /** @constant */
            adult: true;
            /** @constant */
            pilot: true;
            /** @constant */
            product: true;
        };
        ConsentResponse: {
            /** @constant */
            contractVersion: 1;
            data: {
                /** @constant */
                accepted: true;
            };
        };
        CreateSocialInteractionRequest: {
            /** Format: uuid */
            interactionId: string;
            /** Format: uuid */
            recipientMembershipId: string;
            /** @constant */
            kind: "reaction";
            /** @enum {string} */
            body: "strong" | "fire" | "cheer";
        } | {
            /** Format: uuid */
            interactionId: string;
            /** Format: uuid */
            recipientMembershipId: string;
            /** @constant */
            kind: "message";
            /** @description Canonical message without surrounding whitespace. */
            body: string;
        };
        SocialInteractionResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["SocialInteractionResult"];
        };
        SocialInteractionResult: {
            /** Format: uuid */
            interactionId: string;
        };
        DeletedAccountResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["DeletedAccountResult"];
        };
        PendingAccountDeletionResponse: {
            /** @constant */
            contractVersion: 1;
            data: {
                /** Format: uuid */
                accountId: string;
                /** @constant */
                authDeletion: "pending";
            };
        };
        DeletedAccountResult: {
            /** Format: uuid */
            accountId: string;
        };
        WeeklyTargetResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["WeeklyTargetResult"];
        };
        WeeklyTargetResult: {
            /** Format: uuid */
            membershipId: string;
            weeklyTarget: number;
        };
        WeeklyTargetContextResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["WeeklyTargetContext"];
        };
        WeeklyTargetContext: {
            /** Format: uuid */
            membershipId: string;
            recurringTarget: number;
            lockedTarget: number | null;
            nextWeekStartsAt: components["schemas"]["UtcInstant"] | null;
            memberCount: number;
            timeZone: string;
        };
        GroupMembershipResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["GroupMembershipResult"];
        };
        GroupMembershipResult: {
            /** Format: uuid */
            membershipId: string;
        };
        CurrentGroupMembershipResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["CurrentGroupMembershipResult"];
        };
        CurrentGroupMembershipResult: {
            membership: {
                /** Format: uuid */
                groupId: string;
                /** Format: uuid */
                membershipId: string;
            } | null;
        };
        MemberHomeResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["MemberHomeResult"];
        };
        MemberHomeResult: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            groupId: string;
            accountabilityWeekId: components["schemas"]["Uuid"] | null;
            weekStatus: ("active" | "provisional" | "attained" | "missed" | "excepted" | "ended_without_result") | null;
            lockedTarget: number | null;
            completedWorkoutCount: number;
            needsYouCount: number;
            friendActivity: components["schemas"]["MemberHomeFriendActivity"][];
            seasonStandings: components["schemas"]["MemberHomeSeasonStanding"][];
            rebuiltAt: components["schemas"]["UtcInstant"];
        };
        MemberHomeFriendActivity: {
            /** Format: uuid */
            membershipId: string;
            lockedTarget: number | null;
            completedWorkoutCount: number;
            weekStatus: ("active" | "provisional" | "attained" | "missed" | "excepted" | "ended_without_result") | null;
        };
        MemberHomeSeasonStanding: {
            /** Format: uuid */
            membershipId: string;
            crowns: number;
            rank: number;
            cochampion: boolean;
        };
        NotificationCenterResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["NotificationCenterResult"];
        };
        NotificationCenterResult: {
            unread: components["schemas"]["NotificationItem"][];
            read: components["schemas"]["NotificationItem"][];
        };
        NotificationItem: {
            /** Format: uuid */
            notificationId: string;
            /** @enum {string} */
            class: "social" | "action";
            priority: number;
            templateKey: string;
            /** @enum {string} */
            state: "unread" | "read";
            createdAt: components["schemas"]["UtcInstant"];
            relevantUntil: components["schemas"]["UtcInstant"];
        };
        NotificationOpenResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["NotificationOpenResult"];
        };
        NotificationOpenResult: {
            route: string;
        };
        GroupInvitationResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["GroupInvitationResult"];
        };
        GroupInvitationResult: {
            /** Format: uuid */
            invitationId: string;
            token: string;
            expiresAt: components["schemas"]["UtcInstant"];
        };
        RevokedGroupInvitationResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["RevokedGroupInvitationResult"];
        };
        RevokedGroupInvitationResult: {
            /** Format: uuid */
            invitationId: string;
            /** @constant */
            status: "revoked";
        };
        GroupRosterResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["GroupRosterResult"];
        };
        GroupRosterResult: {
            groupName: string;
            members: components["schemas"]["GroupRosterMember"][];
        };
        GroupRosterMember: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
            weeklyTarget: number;
            creator: boolean;
        };
        PendingGroupInvitationsResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["PendingGroupInvitation"][];
        };
        PendingGroupInvitation: {
            /** Format: uuid */
            invitationId: string;
            /** Format: email */
            email: string;
            expiresAt: components["schemas"]["UtcInstant"];
        };
        SubmitWorkoutCheckinResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["WorkoutCheckinResult"];
        };
        WorkoutCheckinResult: {
            /** Format: uuid */
            workoutCheckinId: string;
            currentWeekCount: number;
        };
        CurrentWeekProgressResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["CurrentWeekProgressItem"][];
        };
        CurrentWeekProgressItem: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
            lockedTarget: number;
            completedWorkoutCount: number;
            activityTypes: ("strength" | "cardio" | "class" | "sport" | "mixed")[];
        };
        FinalizedWeeklyHistoryResponse: {
            /** @constant */
            contractVersion: 1;
            data: components["schemas"]["FinalizedWeeklyHistoryItem"][];
        };
        FinalizedWeeklyHistoryItem: {
            /** Format: uuid */
            membershipId: string;
            displayName: string;
            startsAt: components["schemas"]["UtcInstant"];
            endsAt: components["schemas"]["UtcInstant"];
            lockedTarget: number;
            completedWorkoutCount: number;
            /** @enum {string} */
            outcome: "attained" | "missed";
        };
        /** Format: date-time */
        UtcInstant: string;
        /** Format: uuid */
        Uuid: string;
    };
    responses: {
        /** @description Request, authorization, conflict, or domain failure */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        GroupId: string;
        InvitationId: string;
        MembershipId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getV1Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned local service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    enrollByInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Uniform eligibility response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            503: components["responses"]["ApiError"];
        };
    };
    recordTrueMvpConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Age and pilot/product consent recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            503: components["responses"]["ApiError"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Account deleted or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedAccountResponse"];
                };
            };
            /** @description DB cutoff committed; Auth hard deletion pending retry */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingAccountDeletionResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getAccountDisplayName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Account display name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDisplayNameResponse"];
                };
            };
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    setAccountDisplayName: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDisplayNameRequest"];
            };
        };
        responses: {
            /** @description Account display name saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDisplayNameResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    submitWorkoutCheckin: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitWorkoutCheckinRequest"];
            };
        };
        responses: {
            /** @description Check-in accepted or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitWorkoutCheckinResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    issueGroupInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueGroupInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation issued or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInvitationResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    revokeGroupInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                invitationId: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokedGroupInvitationResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    acceptGroupInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptGroupInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation accepted or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    previewGroupInvitation: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eligible invitation preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    leaveGroup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership ended voluntarily or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getWeeklyTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current member target and authoritative next week boundary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyTargetContextResponse"];
                };
            };
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    setWeeklyTarget: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWeeklyTargetRequest"];
            };
        };
        responses: {
            /** @description Weekly target scheduled or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyTargetResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getCurrentGroupMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative current Group membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentGroupMembershipResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getMemberHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized task-first member Home read model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberHomeResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-owned live canonical in-app notifications grouped by read state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationCenterResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    openNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live-authorized notification destination or safe recovery route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOpenResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    createSocialInteraction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSocialInteractionRequest"];
            };
        };
        responses: {
            /** @description Social interaction created or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocialInteractionResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                groupId: components["parameters"]["GroupId"];
                membershipId: components["parameters"]["MembershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed or idempotently replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            409: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Group roster visible to current members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRosterResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    listPendingGroupInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending invitations visible to Group creator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingGroupInvitationsResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getCurrentWeekProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Group member targets and check-in counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentWeekProgressResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getFinalizedWeeklyHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group history visible under authoritative membership rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizedWeeklyHistoryResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
}
